# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ps_logic/ps_logic.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_logic || ORIG_REF_NAME==ps_logic}]

# IP: bd/ps_logic/ip/ps_logic_processing_system7_0_0/ps_logic_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_logic_processing_system7_0_0 || ORIG_REF_NAME==ps_logic_processing_system7_0_0}]

# XDC: bd/ps_logic/ip/ps_logic_processing_system7_0_0/ps_logic_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ps_logic_processing_system7_0_0 || ORIG_REF_NAME==ps_logic_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/ps_logic/ps_logic_ooc.xdc
