# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z020clg400-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/jack/Sandox/MicroZED/mzed/mzed.cache/wt [current_project]
set_property parent.project_path /home/jack/Sandox/MicroZED/mzed/mzed.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:microzed_7020:part0:1.0 [current_project]
add_files /home/jack/Sandox/MicroZED/mzed/mzed.srcs/sources_1/bd/ps_logic/ps_logic.bd
set_property used_in_implementation false [get_files -all /home/jack/Sandox/MicroZED/mzed/mzed.srcs/sources_1/bd/ps_logic/ip/ps_logic_processing_system7_0_0/ps_logic_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/jack/Sandox/MicroZED/mzed/mzed.srcs/sources_1/bd/ps_logic/ps_logic_ooc.xdc]
set_property is_locked true [get_files /home/jack/Sandox/MicroZED/mzed/mzed.srcs/sources_1/bd/ps_logic/ps_logic.bd]

read_verilog -library xil_defaultlib /home/jack/Sandox/MicroZED/mzed/mzed.srcs/sources_1/imports/hdl/ps_logic_wrapper.v
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
catch { write_hwdef -file ps_logic_wrapper.hwdef }
synth_design -top ps_logic_wrapper -part xc7z020clg400-1
write_checkpoint -noxdef ps_logic_wrapper.dcp
catch { report_utilization -file ps_logic_wrapper_utilization_synth.rpt -pb ps_logic_wrapper_utilization_synth.pb }
